---
- name: Install Nginx and dependencies
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: apt get update
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    - name: Install Nginx
        apt: Nginx
        update_cache: true
        state: latest