version: 0.2
phases:
  install:
    commands:
      - ls
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.7/packer_1.7.7_linux_amd64.zip
      - unzip -f packer.zip
      - ls
      - sudo mv packer /usr/local/bin

  build:
    commands:
      - packer build packer-data/web-server.json
